'use server';

/**
 * @fileOverview A product description improvement AI agent.
 * 
 * - improveProductDescription - A function that enhances product descriptions using AI.
 * - ImproveProductDescriptionInput - The input type for the improveProductDescription function.
 * - ImproveProductDescriptionOutput - The return type for the improveProductDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveProductDescriptionInputSchema = z.object({
  keywords: z
    .string()
    .describe('Keywords related to the product, separated by commas.'),
  existingDescription: z.string().describe('The current product description.'),
  productData: z.string().describe('Additional data about the product.'),
});

export type ImproveProductDescriptionInput = z.infer<
  typeof ImproveProductDescriptionInputSchema
>;

const ImproveProductDescriptionOutputSchema = z.object({
  improvedDescription: z
    .string()
    .describe('The improved product description generated by the AI.'),
});

export type ImproveProductDescriptionOutput = z.infer<
  typeof ImproveProductDescriptionOutputSchema
>;

export async function improveProductDescription(
  input: ImproveProductDescriptionInput
): Promise<ImproveProductDescriptionOutput> {
  return improveProductDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveProductDescriptionPrompt',
  input: {schema: ImproveProductDescriptionInputSchema},
  output: {schema: ImproveProductDescriptionOutputSchema},
  prompt: `You are an expert copywriter specializing in writing compelling product descriptions.

  Based on the provided keywords, existing description, and product data, generate an improved product description that is more engaging and likely to attract customers.

  Keywords: {{{keywords}}}
  Existing Description: {{{existingDescription}}}
  Product Data: {{{productData}}}

  Improved Description:`,
});

const improveProductDescriptionFlow = ai.defineFlow(
  {
    name: 'improveProductDescriptionFlow',
    inputSchema: ImproveProductDescriptionInputSchema,
    outputSchema: ImproveProductDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
